spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
  mvc:
    view:
      prefix: /template/
      suffix: .jsp
